metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.logstash:
  hosts: ['logstash:5044']

setup.kibana:
  host: "http://kibana:5601"
  protocol: "http"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
#  ssl.enabled: false
#  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
