version: "3.7"

services:
  kibana:
    image: $IMG_KIBANA:$ELASTIC_VERSION
    container_name: kibana
    restart: always
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - CERTS_DIR=$CERTS_DIR
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - es-certs:$CERTS_DIR
    ports:
      - 5601:5601
    networks:
      - es-net
    external_links: ['es01', 'es02', 'es03']

volumes:
  es-certs:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/develop/data/es-certs'

networks:
  es-net:
    external: true
    name: es-net
