filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/jenkins/**
  encoding: UTF-8
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  include_lines: ['^\[[0-9]{4}-[0-9]{2}-[0-9]{2}']

processors:
- drop_fields:
    fields: ["log.offset", "host.name", "agent.id", "agent.type", "agent.version", "agent.hostname", "agent.ephemeral_id", "input.type", "ecs.version"]

output.logstash:
  hosts: ['logstash:5044']

#output.elasticsearch:
#  hosts: ['es01:9200']
#  protocol: "http"
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
#  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_USERNAME:}'
  protocol: "http"
#  ssl.enabled: false
#  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
