version: "3.7"

services:
  heartbeat:
    image: $IMG_HEARTBEAT:$ELASTIC_VERSION
    container_name: heartbeat
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    networks: ['es-net']
    external_links: ['es01', 'es02', 'es03', 'kibana']
    healthcheck:
      test: heartbeat test config
      interval: 60s
      timeout: 30s
      retries: 5

networks:
  es-net:
    external: true
    name: es-net
