version: "3.7"

services:
  enterprisesearch:
    image: $IMG_ENTERPRISE_SEARCH:$ELASTIC_VERSION
    container_name: enterprise-search
    restart: always
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - CERTS_DIR=$CERTS_DIR
      - ENT_SEARCH_DEFAULT_PASSWORD=$ELASTIC_PASSWORD
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./config/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml
      - es-certs:$CERTS_DIR
    ports:
      - 3002:3002
    networks:
      - es-net
    external_links: ['es01', 'es02', 'es03']

volumes:
  es-certs:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/develop/data/es-certs'

networks:
  es-net:
    external: true
    name: es-net
