journalbeat.inputs:
- paths: []
  seek: cursor

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:es01:9200}'
  protocol: "http"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
#  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  protocol: "http"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
#  ssl.enabled: false
#  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]
