version: "3.7"

services:
  logstash:
    build: .
    image: logstash
    container_name: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports: 
      - '9600:9600'
      - '5044:5044'
    networks: ['es-net']
    external_links: ['es01', 'es02', 'es03']

networks:
  es-net:
    external: true
    name: es-net
